version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visit-counter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ehp0p2x4pvzd"
s3_prefix = "visit-counter"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
